#!/usr/bin/python3
"""
    Serializes instance to json and deserializes to instances
"""
import json


class FileStorage():
    __file_path: str =  "file.json"
    __objects: dict = {}

    def __init__(self):
        """Constructors"""
        pass

    def all(self):
        """Returns the dictionary object"""
        return File 7o__objects

    def new(self, obj):
        """Sets ib __objects"""
        
